config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "sessions#home"
  get '/login', controller: :sessions, action: :new
  post '/login', controller: :sessions, action: :create
  get '/signup', controller: :users, action: :new
  post '/signup', controller: :users, action: :create
  get '/logout', controller: :sessions, action: :destroy
  get '/clock-in', controller: :clocking_events, action: :clock_in
  post '/clock-out', controller: :clocking_events, action: :clock_out
  post '/clocking-events/:id', controller: :clocking_events, action: :update, as: :clocking_event
  resources :users, only: [:index, :show]
  resources :clocking_events, only: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clocking_event.rb
class ClockingEvent < ApplicationRecord
  belongs_to :user
  validates_presence_of :clock_in_time
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :clocking_events
  validates_presence_of :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates_uniqueness_of :email
  validates_presence_of :password, length: { minimum: 6 }
  validates_uniqueness_of :last_name, :first_name
  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionHelper

  private

    def logged_in_user
      unless logged_in?
        flash[:error] = "Please log in"
        redirect_to login_url
      end
    end
end

app/controllers/clocking_events_controller.rb
class ClockingEventsController < ApplicationController
  before_action :logged_in_user

  def clock_in
    ClockingEvent.create(clock_in_time: DateTime.now, user_id: current_user.id)
    flash[:notice] = "Clocked In"
    redirect_to user_url current_user
  end

  def clock_out
    clocking_event = current_user.clocking_events.last
    clocking_event.clock_out_time = DateTime.now
    clocking_event.clock_out_reason = clock_out_params[:clock_out_reason]
    clocking_event.save
    flash[:notice] = "Clocked Out"
    redirect_to user_url current_user
  end

  def edit
    @clocking_event = ClockingEvent.find_by(id: params[:id], user_id: current_user.id)
    @user = current_user
    render template: "users/show"
  end

  def update
    @clocking_event = ClockingEvent.find_by(id: params[:id], user_id: current_user.id)
    clock_in_time = get_datetime(params[:clock_in_date], params[:clock_in_time])
    clock_out_time = get_datetime(params[:clock_out_date], params[:clock_out_time])

    if clock_in_time > DateTime.now
      flash[:error] = "Clock in datetime is beyond current datetime"
      redirect_back fallback_location: { action: :edit, id: params[:id]} and return
    end

    if clock_out_time && (clock_out_time > clock_in_time)
      flash[:error] = "Clock in datetime is beyond clock out datetime"
      redirect_back fallback_location: { action: :edit, id: params[:id]} and return
    end

    result = @clocking_event.update(
      clock_in_time: clock_in_time,
      clock_out_time: clock_out_time,
      clock_out_reason: params[:clock_out_reason]
    )

    unless result
      flash[:error] = "Failed to update"
      redirect_back fallback_location: { action: :edit, id: params[:id]} and return
    end
    flash[:success] = "Time entry was updated successfully"
    redirect_to user_url current_user
  end

  private

  def clock_out_params
    params.permit(:clock_out_reason)
  end

  def update_params
    params.permit(
      :clock_in_date, :clock_out_date, :clock_in_time,
      :clock_out_time, :clock_out_reason
    )
  end

  def get_datetime(date, time)
    DateTime.strptime("#{date} #{time}", '%Y-%m-%d %H:%M') unless date.nil? && time.nil?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to user_url current_user and return if logged_in?
    render template: "sessions/new"
  end;

  def home
    render template: "home"
  end

  def create
    user_facade = Controllers::UsersFacade.new
    @user = user_facade.authenticate_user(login_params[:email].downcase, login_params[:password])
    respond_to do |format|
      format.html do
        unless user_facade.errors.empty?
          flash[:errors] = user_facade.errors
          redirect_to login_url, status: 401
          return
        end
        log_in @user
        flash[:success] = "Welcome to ClockIT"
        redirect_to user_url @user, status: 200
      end
    end
  end

  def destroy
    logout
    redirect_to root_url
  end

  private

    def login_params
      params.permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    user_facade = Controllers::UsersFacade.new
    user_facade.create_user user_params
    respond_to do |format|
      format.html do
        unless user_facade.errors.empty?
          flash[:errors] = user_facade.errors
          render :new, status: 400
          return
        end
        flash[:success] = "Registration was successful. Please log in with your credentials"
        render template: "sessions/new" , status: 200
      end
    end
  end

  def show
    @user = current_user
    render "users/show"
  end

  private

  def user_params
    params.permit(
      :email, :password, :password_confirmation,
      :first_name, :last_name, :middle_name
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clocking_event_helper.rb
module ClockingEventHelper
  def format_time(clocking_event_time)
    clocking_event_time.localtime.to_formatted_s(:long) unless clocking_event_time.nil?
  end

  def already_clocked_in?(user)
    return false if user.clocking_events.empty?
    user.clocking_events.last.clock_out_time.nil?
  end

  def extract_date(datetime)
    return if datetime.nil?
    datetime.localtime.strftime("%Y-%m-%d")
  end

  def extract_time(datetime)
    return if datetime.nil?
    datetime.localtime.strftime("%H:%M")
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClockIT</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="signup-container">
  <div class="signup-container-wrapper d-flex justify-content-center">
    <% if flash[:errors] %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <% flash[:errors].each do |error| %>
          <p><%= error %><p>
        <% end %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <div class="signup-section">
      <h2>Register</h2>
      <form class="row g-3 needs-validation" method="post" action="/signup">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token.to_s %>" />
        <div class="col-md-12">
          <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Lastname" required>
        </div>
        <div class="col-md-12">
          <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Firstname" required>
        </div>
        <div class="col-md-12">
          <input type="text" class="form-control" id="middle_name" name="middle_name" placeholder="Othername">
        </div>
        <div class="col-md-12">
          <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
        </div>
        <div class="col-md-12">
          <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
        </div>
        <div class="col-md-12">
          <input type="password" class="form-control" id="confirm-password" name="password_confirmation" placeholder="Confirm Password" required>
        </div>
        <div class="d-grid ">
          <button class="btn btn-primary" type="submit">Register</button>
        </div>
      </form>
      <a href='/login'>Already have an account? Log in here!</a>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="<%= root_url %>">
      ClockIT
    </a>
    <div class="dropdown">
      <button style="color: white; border: 0;" class="btn btn-outline-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
        <%= @user.last_name.downcase %> <%= @user.first_name.downcase %>
      </button>
      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
        <li><a class="dropdown-item" href="<%= logout_url %>">logout</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="show-user-container">
  <div class="show-user-container-wrapper d-flex justify-content-center">
    <% if flash[:error] %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= flash[:error] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if flash[:success] %>
      <div class="alert alert-success alert-dismissible fade show" role="alert" style="position: absolute; top: 0.5rem;">
        <%= flash[:success] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if @clocking_event %>
      <div class="update-clocking-event-section container">
        <h2>Update Time Entry</h2>
        <form class="row g-3" action="<%= clocking_event_url @clocking_event %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token.to_s %>" />
          <div class="col-md-6">
            <label for="clock_in_date" class="form-label">Clock in Date</label>
            <input type="date" class="form-control" id="clock_in_date" name="clock_in_date" value="<%= extract_date(@clocking_event.clock_in_time) %>" required>
          </div>
          <div class="col-md-6">
            <label for="clock_in_time" class="form-label">Clock in Time</label>
            <input type="time" class="form-control" id="clock_in_time" name="clock_in_time" value="<%= extract_time(@clocking_event.clock_in_time) %>" required>
          </div>
          <div class="col-md-6">
            <label for="clock_out_date" class="form-label">Clock out Date</label>
            <input type="date" class="form-control" id="clock_out_date" name="clock_out_date" value="<%= extract_date(@clocking_event.clock_out_time) %>" required <% if already_clocked_in? @user %><%= "disabled" %> <% end %>>
          </div>
          <div class="col-md-6">
            <label for="clock_out_time" class="form-label">Clock out Time</label>
            <input type="time" class="form-control" id="clock_out_time" name="clock_out_time" value="<%= extract_time(@clocking_event.clock_out_time) %>"  required <% if already_clocked_in? @user %><%= "disabled" %> <% end %> >
          </div>
          <div class="mb-3">
            <label for="clock_out_time" class="form-label">Clock Out Reason</label>
            <textarea class="form-control" style="font-size: 0.8rem;" id="message-text" name="clock_out_reason" placeholder="Please give reason for clocking out"  <% if already_clocked_in? @user %><%= "disabled" %> <% end %>><%= @clocking_event.clock_out_reason %></textarea>
          </div>
          <div class="d-grid gap-2" style="margin-top: 0.5rem; margin-bottom: 2rem;">
            <button type="submit" class="btn btn-primary">Update</button>
          </div>
        </form>
        <a href="<%= user_url @user %>">Go Back</a>
      </div>
    <% else %>
      <div class="container" style="margin-top: 2rem; margin-bottom: 2rem;">
        <div class="d-grid gap-2" style="margin: 2rem 0;">
          <% if already_clocked_in? @user %>
            <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#clockOutModal">Click to Clock Out</button>
          <% else %>
            <a class="btn btn-primary" href="<%= clock_in_url %>">Click to Clock In</a>
          <% end %>
        </div>
        <h1> Time Entries </h1>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Clock In Time</th>
              <th scope="col">Clock Out Time</th>
              <th scope="col">Reason for Clocking Out</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @user.clocking_events.each do |clocking_event| %>
              <tr>
                <td><%= format_time(clocking_event.clock_in_time) %></td>
                <td><%= format_time(clocking_event.clock_out_time) %></td>
                <td><%= clocking_event.clock_out_reason %></td>
                <td><a class="btn btn-primary" href="<%= edit_clocking_event_url clocking_event %>">update</a></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>


<div class="modal fade" style="margin-top: 4rem;" id="clockOutModal" tabindex="-1" aria-labelledby="clockOutModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h6 class="modal-title" id="exampleModalLabel">Clock Out Reason</h6>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="<%= clock_out_url %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token.to_s %>" />
          <div class="mb-3">
            <textarea class="form-control" style="font-size: 0.8rem;" id="message-text" name="clock_out_reason" placeholder="Please give reason for clocking out"></textarea>
          </div>
          <div class="d-grid gap-2" style="margin: 1rem 0;">
            <button type="submit" class="btn btn-danger">Clock Out</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>